# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  amdvlk = {
    pname = "amdvlk";
    version = "1f3670a49fc05e5e57424ac3f1faa8c8472240f7";
    src = fetchgit {
      url = "https://github.com/GPUOpen-Drivers/AMDVLK.git";
      rev = "1f3670a49fc05e5e57424ac3f1faa8c8472240f7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Fd2DwQfbYXOlanYfEWYe64cSIiPkrLxz4CWIzAqQug0=";
    };
    date = "2024-08-29";
  };
  arkenfox = {
    pname = "arkenfox";
    version = "128.0";
    src = fetchFromGitHub {
      owner = "arkenfox";
      repo = "user.js";
      rev = "128.0";
      fetchSubmodules = false;
      sha256 = "sha256-XLswsa2u2qsUPsLYRYn6lwis7VwSjAW6BRNdI4brbSM=";
    };
  };
  bruno-deb-x86_64-linux = {
    pname = "bruno-deb-x86_64-linux";
    version = "1.28.0";
    src = fetchurl {
      url = "https://github.com/usebruno/bruno/releases/download/v1.28.0/bruno_1.28.0_amd64_linux.deb";
      name = "bruno-x86_64-linux.zip";
      sha256 = "sha256-6VY59pF6LJ1FHM0C1DKmPC9pPTVCJJ6nunj5J99gd/A=";
    };
  };
  btop = {
    pname = "btop";
    version = "v1.3.2";
    src = fetchFromGitHub {
      owner = "aristocratos";
      repo = "btop";
      rev = "v1.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-kjSyIgLTObTOKMG5dk49XmWPXZpCWbLdpkmAsJcFliA=";
    };
  };
  bun-x86_64-linux = {
    pname = "bun-x86_64-linux";
    version = "1.1.27";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.1.27/bun-linux-x64.zip";
      name = "bun-x86_64-linux.zip";
      sha256 = "sha256-Ir0EQH+bnHPwOTakrO/ZQ6pyeOWvhu5bK5j+YLN8Myc=";
    };
  };
  catppuccin-btop = {
    pname = "catppuccin-btop";
    version = "1.0.0";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-J3UezOQMDdxpflGax0rGBF/XMiKqdqZXuX4KMVGTxFk=";
    };
  };
  catppuccin-gtk = {
    pname = "catppuccin-gtk";
    version = "23b52b5b9cde1e11c07315e79a55804d2ac77e3a";
    src = fetchgit {
      url = "https://github.com/catppuccin/gtk.git";
      rev = "23b52b5b9cde1e11c07315e79a55804d2ac77e3a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4tBGN+Rra6C2pjkoLWmNqaYUwpzALsYrn4tkYGUtQl4=";
    };
    date = "2024-06-02";
  };
  catppuccin-hyprland = {
    pname = "catppuccin-hyprland";
    version = "c388ac55563ddeea0afe9df79d4bfff0096b146b";
    src = fetchgit {
      url = "https://github.com/catppuccin/hyprland.git";
      rev = "c388ac55563ddeea0afe9df79d4bfff0096b146b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xSa/z0Pu+ioZ0gFH9qSo9P94NPkEMovstm1avJ7rvzM=";
    };
    date = "2024-06-19";
  };
  catppuccin-hyprlock = {
    pname = "catppuccin-hyprlock";
    version = "958e70b1cd8799defd16dee070d07f977d4fd76b";
    src = fetchgit {
      url = "https://github.com/catppuccin/hyprlock.git";
      rev = "958e70b1cd8799defd16dee070d07f977d4fd76b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-l4CbAUeb/Tg603QnZ/VWxuGqRBztpHN0HLX/h8ndc5w=";
    };
    date = "2024-08-06";
  };
  dns-root-hints = {
    pname = "dns-root-hints";
    version = "20240814";
    src = fetchurl {
      url = "https://www.internic.net/domain/named.root";
      sha256 = "sha256-ybmUSpcX1rXxUZ9O94ajvJda8XpNDB0maI0qzKKZd9I=";
    };
  };
  fblog = {
    pname = "fblog";
    version = "v4.10.0";
    src = fetchFromGitHub {
      owner = "brocode";
      repo = "fblog";
      rev = "v4.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-4Yg7gWVBG9GI1ailEbbcslM+XR8L7yjjjvf4dQq/87I=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./fblog-v4.10.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  gluetun = {
    pname = "gluetun";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "qmcgaw/gluetun";
      imageDigest = "sha256:3968a849725534cba47b0a3b9edc16949e5b93bec8cea8cd16b629378d759ad0";
      sha256 = "sha256-AM6RC2wunKQ68iI3ishMJeafGS+PjHgyXd8olCG3oEE=";
      finalImageTag = "latest";
      os = "linux";
      arch = "amd64";
    };
  };
  gluetun-src = {
    pname = "gluetun-src";
    version = "v3.39.0";
    src = fetchFromGitHub {
      owner = "qdm12";
      repo = "gluetun";
      rev = "v3.39.0";
      fetchSubmodules = false;
      sha256 = "sha256-qwImCWplA+9HjHVKDUT5aa7VqwWVPkVB+r1M2ijX7No=";
    };
  };
  go = {
    pname = "go";
    version = "1.23.1";
    src = fetchurl {
      url = "https://go.dev/dl/go1.23.1.src.tar.gz";
      sha256 = "sha256-buROKYN50Ual5aprHFtdX10KM2XqvdcHQebiE0DsOw0=";
    };
  };
  oh-my-posh = {
    pname = "oh-my-posh";
    version = "v23.13.1";
    src = fetchFromGitHub {
      owner = "JanDeDobbeleer";
      repo = "oh-my-posh";
      rev = "v23.13.1";
      fetchSubmodules = false;
      sha256 = "sha256-yGL7WX9b8ogB5CsfrkEJqmB6JxYQdpQ19wGptSAteXM=";
    };
  };
  spectral = {
    pname = "spectral";
    version = "v6.11.1";
    src = fetchFromGitHub {
      owner = "stoplightio";
      repo = "spectral";
      rev = "v6.11.1";
      fetchSubmodules = false;
      sha256 = "sha256-ivuu7kpVJIn2RiFAe/slMffcisVeq7yeG1TwoXMOMeA=";
    };
  };
  standardnotes-desktop-deb-x86_64-linux = {
    pname = "standardnotes-desktop-deb-x86_64-linux";
    version = "3.195.2";
    src = fetchurl {
      url = "https://github.com/standardnotes/app/releases/download/@standardnotes/desktop@3.195.2/standard-notes-3.195.2-linux-amd64.deb";
      name = "standardnotes-desktop-x86_64-linux.deb";
      sha256 = "sha256-8CH2GywiTx2E5s440UwxcFV1sho1SJLwYKIkjhB3DvU=";
    };
  };
  tree-sitter-cql = {
    pname = "tree-sitter-cql";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "shotover";
      repo = "tree-sitter-cql";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-1wJeVajNifxEVe00/YbEyWOsw2ffTjhGfGQnd6a/UhE=";
    };
  };
  vivid-plasma-themes = {
    pname = "vivid-plasma-themes";
    version = "cdcbad3bafca0c7a39fd8e4ccdbe493779e398ec";
    src = fetchgit {
      url = "https://github.com/L4ki/Vivid-Plasma-Themes.git";
      rev = "cdcbad3bafca0c7a39fd8e4ccdbe493779e398ec";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MqXjrJz+c+NoqHDxBb5P4SnNPVGtzkrIsieoT45L+ew=";
    };
    date = "2024-09-07";
  };
  wezterm = {
    pname = "wezterm";
    version = "30345b36d8a00fed347e4df5dadd83915a7693fb";
    src = fetchgit {
      url = "https://github.com/wez/wezterm.git";
      rev = "30345b36d8a00fed347e4df5dadd83915a7693fb";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-By7g1yImmuVba/MTcB6ajNSHeWDRn4gO+p0UOWcCEgE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wezterm-30345b36d8a00fed347e4df5dadd83915a7693fb/Cargo.lock;
      outputHashes = {
        "xcb-imdkit-0.3.0" = "sha256-77KaJO+QJWy3tJ9AF1TXKaQHpoVOfGIRqteyqpQaSWo=";
        "sqlite-cache-0.1.3" = "sha256-sBAC8MsQZgH+dcWpoxzq9iw5078vwzCijgyQnMOWIkk=";
      };
    };
    date = "2024-08-12";
  };
}
