# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  amdvlk = {
    pname = "amdvlk";
    version = "9cf5b703f8fed5c18c79a7306cbe57bb0de71eff";
    src = fetchgit {
      url = "https://github.com/GPUOpen-Drivers/AMDVLK.git";
      rev = "9cf5b703f8fed5c18c79a7306cbe57bb0de71eff";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YHIErtMETQZJVpy4XLXJfV+8oeHFyaZhRZhg3adaSzw=";
    };
    date = "2024-12-23";
  };
  arkenfox = {
    pname = "arkenfox";
    version = "133.0";
    src = fetchFromGitHub {
      owner = "arkenfox";
      repo = "user.js";
      rev = "133.0";
      fetchSubmodules = false;
      sha256 = "sha256-iHj+4UGeB1FVGvOWB9ZZA4aiiJynBxRSFFfJqToYEdQ=";
    };
  };
  bruno-deb-x86_64-linux = {
    pname = "bruno-deb-x86_64-linux";
    version = "1.38.1";
    src = fetchurl {
      url = "https://github.com/usebruno/bruno/releases/download/v1.38.1/bruno_1.38.1_amd64_linux.deb";
      name = "bruno-x86_64-linux.zip";
      sha256 = "sha256-q+POVqdqCXnpJ754E1ZvPyRvWovVDf8jy+eQ94Cn7XU=";
    };
  };
  btop = {
    pname = "btop";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "aristocratos";
      repo = "btop";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-A5hOBxj8tKlkHd8zDHfDoU6fIu8gDpt3/usbiDk0/G0=";
    };
  };
  bun-x86_64-linux = {
    pname = "bun-x86_64-linux";
    version = "1.2.1";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.2.1/bun-linux-x64.zip";
      name = "bun-x86_64-linux.zip";
      sha256 = "sha256-Q4DjmFTLTIqt8jfI9dJwJWSaK0lwXakc4zBm3pWdUug=";
    };
  };
  catppuccin-btop = {
    pname = "catppuccin-btop";
    version = "1.0.0";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-J3UezOQMDdxpflGax0rGBF/XMiKqdqZXuX4KMVGTxFk=";
    };
  };
  catppuccin-gtk = {
    pname = "catppuccin-gtk";
    version = "23b52b5b9cde1e11c07315e79a55804d2ac77e3a";
    src = fetchgit {
      url = "https://github.com/catppuccin/gtk.git";
      rev = "23b52b5b9cde1e11c07315e79a55804d2ac77e3a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4tBGN+Rra6C2pjkoLWmNqaYUwpzALsYrn4tkYGUtQl4=";
    };
    date = "2024-06-02";
  };
  catppuccin-hyprland = {
    pname = "catppuccin-hyprland";
    version = "c388ac55563ddeea0afe9df79d4bfff0096b146b";
    src = fetchgit {
      url = "https://github.com/catppuccin/hyprland.git";
      rev = "c388ac55563ddeea0afe9df79d4bfff0096b146b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xSa/z0Pu+ioZ0gFH9qSo9P94NPkEMovstm1avJ7rvzM=";
    };
    date = "2024-06-19";
  };
  catppuccin-hyprlock = {
    pname = "catppuccin-hyprlock";
    version = "958e70b1cd8799defd16dee070d07f977d4fd76b";
    src = fetchgit {
      url = "https://github.com/catppuccin/hyprlock.git";
      rev = "958e70b1cd8799defd16dee070d07f977d4fd76b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-l4CbAUeb/Tg603QnZ/VWxuGqRBztpHN0HLX/h8ndc5w=";
    };
    date = "2024-08-06";
  };
  dns-root-hints = {
    pname = "dns-root-hints";
    version = "20250129";
    src = fetchurl {
      url = "https://www.internic.net/domain/named.root";
      sha256 = "sha256-axHjPoZx/mCtjFMyewF+kQomdZToI0Wf4NYvT6fXMcY=";
    };
  };
  fblog = {
    pname = "fblog";
    version = "v4.13.1";
    src = fetchFromGitHub {
      owner = "brocode";
      repo = "fblog";
      rev = "v4.13.1";
      fetchSubmodules = false;
      sha256 = "sha256-YOHLw8YCgOGB1Nn2tD+EnicKd/tiMk07OWv+49btbpw=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./fblog-v4.13.1/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  gluetun-src = {
    pname = "gluetun-src";
    version = "v3.40.0";
    src = fetchFromGitHub {
      owner = "qdm12";
      repo = "gluetun";
      rev = "v3.40.0";
      fetchSubmodules = false;
      sha256 = "sha256-CiA+vCKsjMx+LHVYzHh8x+RFY1rrkkZw5/XU/20it2A=";
    };
  };
  go = {
    pname = "go";
    version = "1.23.5";
    src = fetchurl {
      url = "https://go.dev/dl/go1.23.5.src.tar.gz";
      sha256 = "sha256-pvP0u9PmvdYm95tmjyEvu1ZJ2vdQhPt5tnigrk2XQjs=";
    };
  };
  oh-my-posh = {
    pname = "oh-my-posh";
    version = "v24.19.0";
    src = fetchFromGitHub {
      owner = "JanDeDobbeleer";
      repo = "oh-my-posh";
      rev = "v24.19.0";
      fetchSubmodules = false;
      sha256 = "sha256-HwBLFa7CEAYjCcCn9P7wsgsa4po2x5CewcarcPZAjHI=";
    };
  };
  otel-desktop-viewer = {
    pname = "otel-desktop-viewer";
    version = "50bc41bb3810f199e9fe12ebeda286baf0718e4f";
    src = fetchgit {
      url = "https://github.com/CtrlSpice/otel-desktop-viewer.git";
      rev = "50bc41bb3810f199e9fe12ebeda286baf0718e4f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xqfNokFCgRytA0sf5YEojxKKt2tH5mJbstLgk/sbyPw=";
    };
    date = "2025-01-29";
  };
  otel-tui-x86_64-linux = {
    pname = "otel-tui-x86_64-linux";
    version = "0.4.0";
    src = fetchurl {
      url = "https://github.com/ymtdzzz/otel-tui/releases/download/v0.4.0/otel-tui_Linux_x86_64.tar.gz";
      sha256 = "sha256-WG7Zf/aZI7TVWdtOTtFLau2vlAGJnPi5hrqfQuoglI0=";
    };
  };
  oxc = {
    pname = "oxc";
    version = "0.15.8";
    src = fetchurl {
      url = "https://github.com/oxc-project/oxc/archive/refs/tags/oxlint_v0.15.8.tar.gz";
      sha256 = "sha256-wWPyQwug3FrFwyHUn4gmXLBlnbIi5V0d7Kwk/E20eTg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./oxc-0.15.8/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  spectral = {
    pname = "spectral";
    version = "v6.14.2";
    src = fetchFromGitHub {
      owner = "stoplightio";
      repo = "spectral";
      rev = "v6.14.2";
      fetchSubmodules = false;
      sha256 = "sha256-yxT+a1XD6HKllCYSpW4/R26ufDwDDdapccf/5nfFBlw=";
    };
  };
  spectral-language-server = {
    pname = "spectral-language-server";
    version = "v1.1.4";
    src = fetchFromGitHub {
      owner = "stoplightio";
      repo = "vscode-spectral";
      rev = "v1.1.4";
      fetchSubmodules = false;
      sha256 = "sha256-0p5aFzaddgSKM62R5Y0K10eCNo9CJkGuJZBhJ2cUF/w=";
    };
  };
  standardnotes-desktop-deb-x86_64-linux = {
    pname = "standardnotes-desktop-deb-x86_64-linux";
    version = "3.195.24";
    src = fetchurl {
      url = "https://github.com/standardnotes/app/releases/download/@standardnotes/desktop@3.195.24/standard-notes-3.195.24-linux-amd64.deb";
      name = "standardnotes-desktop-x86_64-linux.deb";
      sha256 = "sha256-7MZu8GEvm/OYIAor9Kja/z+aKAuke37bg4ZmXAnolUA=";
    };
  };
  tree-sitter-cql = {
    pname = "tree-sitter-cql";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "shotover";
      repo = "tree-sitter-cql";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-1wJeVajNifxEVe00/YbEyWOsw2ffTjhGfGQnd6a/UhE=";
    };
  };
  vivid-plasma-themes = {
    pname = "vivid-plasma-themes";
    version = "6753fc4f3eea176c472e1ea1b5275e699aba0fd8";
    src = fetchgit {
      url = "https://github.com/L4ki/Vivid-Plasma-Themes.git";
      rev = "6753fc4f3eea176c472e1ea1b5275e699aba0fd8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sq9m2m8NXiDZDfN8r0BktfAriErXDWA4MTjh6cKi0z0=";
    };
    date = "2025-01-25";
  };
}
