# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  amdvlk = {
    pname = "amdvlk";
    version = "1f3670a49fc05e5e57424ac3f1faa8c8472240f7";
    src = fetchgit {
      url = "https://github.com/GPUOpen-Drivers/AMDVLK.git";
      rev = "1f3670a49fc05e5e57424ac3f1faa8c8472240f7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Fd2DwQfbYXOlanYfEWYe64cSIiPkrLxz4CWIzAqQug0=";
    };
    date = "2024-08-29";
  };
  arkenfox = {
    pname = "arkenfox";
    version = "128.0";
    src = fetchFromGitHub {
      owner = "arkenfox";
      repo = "user.js";
      rev = "128.0";
      fetchSubmodules = false;
      sha256 = "sha256-XLswsa2u2qsUPsLYRYn6lwis7VwSjAW6BRNdI4brbSM=";
    };
  };
  bruno-deb-x86_64-linux = {
    pname = "bruno-deb-x86_64-linux";
    version = "1.30.1";
    src = fetchurl {
      url = "https://github.com/usebruno/bruno/releases/download/v1.30.1/bruno_1.30.1_amd64_linux.deb";
      name = "bruno-x86_64-linux.zip";
      sha256 = "sha256-PVvRA0UEWuc93fQaHP4K54qkX76l1hpK0Y2LmbWCoRI=";
    };
  };
  btop = {
    pname = "btop";
    version = "v1.4.0";
    src = fetchFromGitHub {
      owner = "aristocratos";
      repo = "btop";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-A5hOBxj8tKlkHd8zDHfDoU6fIu8gDpt3/usbiDk0/G0=";
    };
  };
  bun-x86_64-linux = {
    pname = "bun-x86_64-linux";
    version = "1.1.29";
    src = fetchurl {
      url = "https://github.com/oven-sh/bun/releases/download/bun-v1.1.29/bun-linux-x64.zip";
      name = "bun-x86_64-linux.zip";
      sha256 = "sha256-RnKczYB/IkUYVBnRktCFhHsmvObQovVMfCilqJq3q1g=";
    };
  };
  catppuccin-btop = {
    pname = "catppuccin-btop";
    version = "1.0.0";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "btop";
      rev = "1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-J3UezOQMDdxpflGax0rGBF/XMiKqdqZXuX4KMVGTxFk=";
    };
  };
  catppuccin-gtk = {
    pname = "catppuccin-gtk";
    version = "23b52b5b9cde1e11c07315e79a55804d2ac77e3a";
    src = fetchgit {
      url = "https://github.com/catppuccin/gtk.git";
      rev = "23b52b5b9cde1e11c07315e79a55804d2ac77e3a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4tBGN+Rra6C2pjkoLWmNqaYUwpzALsYrn4tkYGUtQl4=";
    };
    date = "2024-06-02";
  };
  catppuccin-hyprland = {
    pname = "catppuccin-hyprland";
    version = "c388ac55563ddeea0afe9df79d4bfff0096b146b";
    src = fetchgit {
      url = "https://github.com/catppuccin/hyprland.git";
      rev = "c388ac55563ddeea0afe9df79d4bfff0096b146b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xSa/z0Pu+ioZ0gFH9qSo9P94NPkEMovstm1avJ7rvzM=";
    };
    date = "2024-06-19";
  };
  catppuccin-hyprlock = {
    pname = "catppuccin-hyprlock";
    version = "958e70b1cd8799defd16dee070d07f977d4fd76b";
    src = fetchgit {
      url = "https://github.com/catppuccin/hyprlock.git";
      rev = "958e70b1cd8799defd16dee070d07f977d4fd76b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-l4CbAUeb/Tg603QnZ/VWxuGqRBztpHN0HLX/h8ndc5w=";
    };
    date = "2024-08-06";
  };
  dns-root-hints = {
    pname = "dns-root-hints";
    version = "20240919";
    src = fetchurl {
      url = "https://www.internic.net/domain/named.root";
      sha256 = "sha256-I8RXSid7HOE6q7IVcA6qQTOO/7QZQ2/mh7oHVLA/U6g=";
    };
  };
  fblog = {
    pname = "fblog";
    version = "v4.12.0";
    src = fetchFromGitHub {
      owner = "brocode";
      repo = "fblog";
      rev = "v4.12.0";
      fetchSubmodules = false;
      sha256 = "sha256-OZE+jqjsyvHLDJ+6r0txH56afufnl4H9PHcG7XRfxnE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./fblog-v4.12.0/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  gluetun = {
    pname = "gluetun";
    version = "latest";
    src = dockerTools.pullImage {
      imageName = "qmcgaw/gluetun";
      imageDigest = "sha256:33053890f0f703368c4cee603a068490c23fe4d1d6dc2e04a19549825157469d";
      sha256 = "sha256-l6dfOHm161TX7lXeo6Wb89bQNwU8pdCfmseojNcqxh8=";
      finalImageTag = "latest";
      os = "linux";
      arch = "amd64";
    };
  };
  gluetun-src = {
    pname = "gluetun-src";
    version = "v3.39.0";
    src = fetchFromGitHub {
      owner = "qdm12";
      repo = "gluetun";
      rev = "v3.39.0";
      fetchSubmodules = false;
      sha256 = "sha256-qwImCWplA+9HjHVKDUT5aa7VqwWVPkVB+r1M2ijX7No=";
    };
  };
  go = {
    pname = "go";
    version = "1.23.1";
    src = fetchurl {
      url = "https://go.dev/dl/go1.23.1.src.tar.gz";
      sha256 = "sha256-buROKYN50Ual5aprHFtdX10KM2XqvdcHQebiE0DsOw0=";
    };
  };
  oh-my-posh = {
    pname = "oh-my-posh";
    version = "v23.15.1";
    src = fetchFromGitHub {
      owner = "JanDeDobbeleer";
      repo = "oh-my-posh";
      rev = "v23.15.1";
      fetchSubmodules = false;
      sha256 = "sha256-xBKGEwvY5U4p7Rlyv4E5rjzUAiFTsWy0VpWE24v/jVY=";
    };
  };
  spectral = {
    pname = "spectral";
    version = "v6.13.1";
    src = fetchFromGitHub {
      owner = "stoplightio";
      repo = "spectral";
      rev = "v6.13.1";
      fetchSubmodules = false;
      sha256 = "sha256-T9lu1ro7oPOH8CZjTbnBphWHivTLRfCA5x4GFvW27lY=";
    };
  };
  standardnotes-desktop-deb-x86_64-linux = {
    pname = "standardnotes-desktop-deb-x86_64-linux";
    version = "3.195.6";
    src = fetchurl {
      url = "https://github.com/standardnotes/app/releases/download/@standardnotes/desktop@3.195.6/standard-notes-3.195.6-linux-amd64.deb";
      name = "standardnotes-desktop-x86_64-linux.deb";
      sha256 = "sha256-PjwWaIbJfugFovAO+2B+ZTSCKKRa3pzID0eDOFrQRXA=";
    };
  };
  tree-sitter-cql = {
    pname = "tree-sitter-cql";
    version = "v0.2.0";
    src = fetchFromGitHub {
      owner = "shotover";
      repo = "tree-sitter-cql";
      rev = "v0.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-1wJeVajNifxEVe00/YbEyWOsw2ffTjhGfGQnd6a/UhE=";
    };
  };
  vivid-plasma-themes = {
    pname = "vivid-plasma-themes";
    version = "dbc8b5e954ba764f809a9ea725173fa661fd03fe";
    src = fetchgit {
      url = "https://github.com/L4ki/Vivid-Plasma-Themes.git";
      rev = "dbc8b5e954ba764f809a9ea725173fa661fd03fe";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lChdx3UjK0fijR0tkiLZFrRpi3uwL2LkDTlFvUHLb8g=";
    };
    date = "2024-09-27";
  };
  wezterm = {
    pname = "wezterm";
    version = "a2f2c07a29f5c98f6736cde0c86b24887f9fd48a";
    src = fetchgit {
      url = "https://github.com/wez/wezterm.git";
      rev = "a2f2c07a29f5c98f6736cde0c86b24887f9fd48a";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KY/9DpHPLKv68a57CFvtRhnhxsXtJ1UmYMfeo3QH9qs=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./wezterm-a2f2c07a29f5c98f6736cde0c86b24887f9fd48a/Cargo.lock;
      outputHashes = {
        "xcb-imdkit-0.3.0" = "sha256-77KaJO+QJWy3tJ9AF1TXKaQHpoVOfGIRqteyqpQaSWo=";
        "sqlite-cache-0.1.3" = "sha256-sBAC8MsQZgH+dcWpoxzq9iw5078vwzCijgyQnMOWIkk=";
      };
    };
    date = "2024-09-28";
  };
}
