keys:
  - users:
      - &caubut age1clvpkj8ktzrlj6dqmchae7suz2kmmjlye8c8pytje03dx3qth47snhfx4v

creation_rules:
  - path_regex: home/caubut/secrets/secrets.yaml$
    key_groups:
      - age:
          - *caubut
