keys:
  - users:
      - &caubut age1x68uud0er556hq9wcz3taav7u8c9u8ng6ztdvtnawscwg6vn3f8q74t05x
  - hosts:
    # - &beelink-ser7 age1hm5lf4qk84r4wh00atn6hpts7mpdx80adq26wht2e5qh9ewvhyaszfv82d
    #  - &vm age1709qfrwglm75v5x8lpuhryt83k6p6c90npplzzec6a5w8ct93ejscpqpc3

creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *caubut
        # - *beelink-ser7
        #  - *vm
