keys:
  - users:
      - &caubut age1cepr9aqfkt084kmt2683wl5mh376lazqeezwwtfvq33dzrhdpczqyvfqd8

creation_rules:
  - path_regex: home/caubut/secrets/secrets.yaml$
    key_groups:
      - age:
          - *caubut
