[amdvlk]
src.git = "https://github.com/GPUOpen-Drivers/AMDVLK.git"
src.use_commit = true
src.branch = "master"
fetch.git = "https://github.com/GPUOpen-Drivers/AMDVLK.git"

[arkenfox]
src.github = "arkenfox/user.js"
fetch.github = "arkenfox/user.js"

[btop]
src.github = "aristocratos/btop"
fetch.github = "aristocratos/btop"

[bun-x86_64-linux]
src.github = "oven-sh/bun"
src.from_pattern = "bun-v([0-9]+\\.[0-9]+\\.[0-9]+)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/oven-sh/bun/releases/download/bun-v$ver/bun-linux-x64.zip"
url.name = "bun-x86_64-linux.zip"

[bruno-deb-x86_64-linux]
src.github = "usebruno/bruno"
src.from_pattern = "v([0-9]+\\.[0-9]+\\.[0-9]+)"
src.to_pattern = "\\1"
fetch.url = "https://github.com/usebruno/bruno/releases/download/v$ver/bruno_$ver_amd64_linux.deb"
url.name = "bruno-x86_64-linux.zip"

[catppuccin-btop]
src.github = "catppuccin/btop"
fetch.github = "catppuccin/btop"

[catppuccin-gtk]
src.git = "https://github.com/catppuccin/gtk.git"
src.use_commit = true
fetch.git = "https://github.com/catppuccin/gtk.git"

[catppuccin-hyprland ]
src.git = "https://github.com/catppuccin/hyprland.git"
src.use_commit = true
src.branch = "main"
fetch.git = "https://github.com/catppuccin/hyprland.git"

[catppuccin-hyprlock ]
src.git = "https://github.com/catppuccin/hyprlock.git"
src.use_commit = true
src.branch = "main"
fetch.git = "https://github.com/catppuccin/hyprlock.git"

# [catppuccin-python]
# src.github = "catppuccin/python"
# fetch.github = "catppuccin/python"

[dns-root-hints]
src.webpage = "https://www.internic.net/domain/named.root"
src.regex = "version of root zone:\\s+([0-9]{8})"
fetch.url = "https://www.internic.net/domain/named.root"

[fblog]
src.github = "brocode/fblog"
fetch.github = "brocode/fblog"
cargo_locks = ["Cargo.lock"]

[gluetun-src]
src.github = "qdm12/gluetun"
fetch.github = "qdm12/gluetun"

[gluetun]
src.container = "qmcgaw/gluetun"
src.include_regex = "latest"
fetch.docker = "qmcgaw/gluetun"
docker.os = "linux"
docker.arch = "amd64"

[go]
src.webpage = "https://go.dev/dl/?mode=json"
src.regex = "\"version\": \"go([0-9]+\\.[0-9]+\\.[0-9]+)\""
src.from_pattern = "^([0-9]+\\.[0-9]+\\.[0-9]+)$"
src.to_pattern = "\\1"
fetch.url = "https://go.dev/dl/go$ver.src.tar.gz"

[oh-my-posh]
src.github = "JanDeDobbeleer/oh-my-posh"
fetch.github = "JanDeDobbeleer/oh-my-posh"

[spectral]
src.github = "stoplightio/spectral"
fetch.github = "stoplightio/spectral"

[standardnotes-desktop-deb-x86_64-linux]
src.github_tag = "standardnotes/app"
src.include_regex = "^@standardnotes/desktop@[0-9]+\\.[0-9]+\\.[0-9]+$"
src.from_pattern = "^@standardnotes/desktop@([0-9]+\\.[0-9]+\\.[0-9]+)$"
src.to_pattern = "\\1"
fetch.url = "https://github.com/standardnotes/app/releases/download/@standardnotes/desktop@$ver/standard-notes-$ver-linux-amd64.deb"
url.name = "standardnotes-desktop-x86_64-linux.deb"

[tree-sitter-cql]
src.github_tag = "shotover/tree-sitter-cql"
fetch.github = "shotover/tree-sitter-cql"

# [vacuum]
# src.github = "daveshanley/vacuum"
# fetch.github = "daveshanley/vacuum"

[vivid-plasma-themes]
src.git = "https://github.com/L4ki/Vivid-Plasma-Themes.git"
src.use_commit = true
src.branch = "main"
fetch.git = "https://github.com/L4ki/Vivid-Plasma-Themes.git"

[wezterm]
src.git = "https://github.com/wez/wezterm.git"
src.use_commit = true
git.fetchSubmodules = true
src.branch = "main"
fetch.git = "https://github.com/wez/wezterm.git"
cargo_locks = ["Cargo.lock"]
