[arkenfox]
src.github = "arkenfox/user.js"
fetch.github = "arkenfox/user.js"

[btop]
src.github = "aristocratos/btop"
fetch.github = "aristocratos/btop"

[catppuccin-btop]
src.github = "catppuccin/btop"
fetch.github = "catppuccin/btop"

[fblog]
src.github = "brocode/fblog"
fetch.github = "brocode/fblog"
cargo_locks = ["Cargo.lock"]

[oh-my-posh]
src.github = "JanDeDobbeleer/oh-my-posh"
fetch.github = "JanDeDobbeleer/oh-my-posh"

[vivid-plasma-themes]
src.git = "https://github.com/L4ki/Vivid-Plasma-Themes.git"
src.use_commit = true
src.branch = "main"
fetch.git = "https://github.com/L4ki/Vivid-Plasma-Themes.git"
