[arkenfox]
src.github = "arkenfox/user.js"
fetch.github = "arkenfox/user.js"

[btop]
src.github = "aristocratos/btop"
fetch.github = "aristocratos/btop"

[catppuccin-btop]
src.github = "catppuccin/btop"
fetch.github = "catppuccin/btop"

[catppuccin-gtk]
src.git = "https://github.com/catppuccin/gtk.git"
src.use_commit = true
src.branch = "main"
fetch.git = "https://github.com/catppuccin/gtk.git"

[catppuccin-hyprland ]
src.git = "https://github.com/catppuccin/hyprland.git"
src.use_commit = true
src.branch = "main"
fetch.git = "https://github.com/catppuccin/hyprland.git"

[catppuccin-hyprlock ]
src.git = "https://github.com/catppuccin/hyprlock.git"
src.use_commit = true
src.branch = "main"
fetch.git = "https://github.com/catppuccin/hyprlock.git"

[catppuccin-python]
src.github = "catppuccin/python"
fetch.github = "catppuccin/python"

[fblog]
src.github = "brocode/fblog"
fetch.github = "brocode/fblog"
cargo_locks = ["Cargo.lock"]

[oh-my-posh]
src.github = "JanDeDobbeleer/oh-my-posh"
fetch.github = "JanDeDobbeleer/oh-my-posh"

[spectral]
src.github = "stoplightio/spectral"
fetch.github = "stoplightio/spectral"

[standardnotes-linux-amd64-deb]
src.github_tag = "standardnotes/app"
src.include_regex = "^@standardnotes/desktop@[0-9]+\\.[0-9]+\\.[0-9]+$"
src.from_pattern = "^@standardnotes/desktop@([0-9]+\\.[0-9]+\\.[0-9]+)$"
src.to_pattern = "\\1"
fetch.url = "https://github.com/standardnotes/app/releases/download/@standardnotes/desktop@$ver/standard-notes-$ver-linux-amd64.deb"
url.name = "standardnotes-desktop-linux-amd64.deb"

[vacuum]
src.github = "daveshanley/vacuum"
fetch.github = "daveshanley/vacuum"

[vivid-plasma-themes]
src.git = "https://github.com/L4ki/Vivid-Plasma-Themes.git"
src.use_commit = true
src.branch = "main"
fetch.git = "https://github.com/L4ki/Vivid-Plasma-Themes.git"
