#!/usr/bin/env bash

set -euETo pipefail
shopt -s inherit_errexit

NIXOS_CONFIG='../../modules/nixos/config'

check-installer() {
	if [ -e /etc/NIXOS ]; then
		echo -e "\e[1;32mRunning in the NixOS installer environment.\e[0m"
	else
		echo -e "\e[1;31mNot running in the NixOS installer environment.\e[0m"
		exit 1
	fi
}

setup-config() {
	cd $NIXOS_CONFIG
}

run-disko() {
	sudo nix run --extra-experimental-features nix-command --extra-experimental-features flakes \
		github:nix-community/disko -- --mode disko ./disk-config.nix
}

echo "hello world" # TODO: remove

check-installer
setup-config
run-disko
