#!/usr/bin/env bash

set -euETo pipefail
shopt -s inherit_errexit

NIXOS_CONFIG="$(dirname "$0")/../../modules/nixos"

check-installer() {
	if [ -e /etc/NIXOS ]; then
		echo -e "\e[1;32mRunning in the NixOS installer environment.\e[0m"
	else
		echo -e "\e[1;31mNot running in the NixOS installer environment.\e[0m"
		exit 1
	fi
}

run-disko() {
	sudo nix run --extra-experimental-features 'nix-command flakes' \
		github:nix-community/disko -- --mode disko "$NIXOS_CONFIG/disk-config.nix"
}

setup-files() {
	sudo mkdir /mnt/etc
	nix flake clone --extra-experimental-features 'nix-command flakes' github:higherorderfunctor/nixos-config?ref=feat/disk-config --dest /mnt/etc/nixos
	cd /mnt/etc/nixos
}

install-nixos() {
	ARCH=$(uname -m)

	case "$ARCH" in
	x86_64)
		FLAKE_TARGET="x86_64-linux"
		;;
	aarch64)
		FLAKE_TARGET="aarch64-linux"
		;;
	*)
		echo -e "${RED}Unsupported architecture: $ARCH${CLEAR}"
		exit 1
		;;
	esac

	sudo nixos-rebuild --extra-experimental-features 'nix-command flakes' --flake github:higherorderfunctor/nixos-config?ref=feat/disk-config switch
	# sudo nixos-install --flake .#beelink-ser7 "$@"
	# TODO: sudo nixos-install --flake .#$FLAKE_TARGET "$@"
	sudo chmod -R 775 /mnt/etc/nixos
}

check-installer
run-disko
setup-files
install-nixos
