#!/usr/bin/env bash

set -euETo pipefail
shopt -s inherit_errexit

check_installer() {
	if [ -e /etc/NIXOS ]; then
		echo -e "\e[1;32mRunning in the NixOS installer environment.\e[0m"
	else
		echo -e "\e[1;31mNot running in the NixOS installer environment.\e[0m"
		exit 1
	fi
}
run_disko() {
	sudo nix run --extra-experimental-features nix-command --extra-experimental-features flakes \
		github:nix-community/disko -- --mode disko ./nixos/disk-config.nix
}

echo "hello world" # TODO: remove

check_installer
run_disko
