#!/usr/bin/env bash

print-msg() {
  echo -en "\033[1;34m${*}\033[0m"
}

print-info() {
  echo -en "\033[1;32m${*}\033[0m"
}

print-warning() {
  >&2 echo -en "\033[1;33m${*}\033[0m"
}

print-error() {
  >&2 echo -en "\033[1;31m${*}\033[0m"
  exit 1
}

readonly -A ARCH_LIST=(
  [x86_64]=true
  [aarch64]=true
)

check-arch() {
  declare -A arch_list
  for key in "$@"; do
    if [[ -v ARCH_LIST[$key] ]]; then
      arch_list[$key]=true
    else
      print-error "\nERROR: Unknown architecture: '$key'\n"
    fi
  done
  if [[ -v arch_list[$(uname -m)] ]]; then
    true
  else
    false
  fi
}

run-module() {
  local FILE BASENAME MODULE
  read -r FILE < <(caller 0 | cut -d' ' -f3)
  BASENAME=$(basename "$FILE")
  MODULE=${BASENAME:1}
  MODULE_NAME=${MODULE/_/-}
  # check if secure module
  print-info "=> $(printf "%-20s" "$MODULE_NAME")"
  if [[ "$1" == true ]] && [[ "${DOTFILES_SECURE:-false}" == false ]]; then
    print-warning "skipped (--no-secure)\n"
    return
  fi
  if ! check-arch "${@:2}"; then
    print-warning "skipped (unsupported arch '$(uname -m)')\n"
    return
  fi
  echo ""
  "update-$MODULE_NAME"
}
