#!/usr/bin/env bash

update-keybase() (
  if ! command -v run_keybase &> /dev/null; then
    print-info "==> installing\n"
    curl --remote-name https://prerelease.keybase.io/keybase_amd64.deb
    sudo apt install ./keybase_amd64.deb
    rm keybase_amd64.deb
  fi
)

run-module true x86_64
