#!/usr/bin/env bash

update-zsh() (
  # set shell
  if [[ "$(basename -- "$SHELL")" != "zsh" ]]; then
    print-info "==> updating user shell\n"
    (set -x && chsh -s "$(command -v zsh)" "$USER")
  fi

  # install custom git completions
  if [[ ! -f "$HOME/.config/zsh/completions/_git" ]]; then
    print-info "==> updating git completions\n"
    (
      set -x
      curl -fLo "$HOME/.config/zsh/completions/_git" \
        --create-dirs \
        "https://raw.githubusercontent.com/git/git/v$(git --version | cut -d' ' -f3)/contrib/completion/git-completion.zsh"
    )
  fi
)

run-module true x86_64
