{
  imports = [
    # ./lshw.nix
    # ./pciutils.nix
    # ./usbutils.nix
    ./alejandra.nix
    ./aspell.nix
    ./bash.nix
    ./beautysh.nix
    ./bitwarden.nix
    ./bun.nix
    ./cmake.nix
    ./curl.nix
    ./deadnix.nix
    ./dircolors.nix
    ./fblog.nix
    ./fd.nix
    ./fzf.nix
    ./gawk.nix
    ./gcc.nix
    ./git.nix
    ./gnumake.nix
    ./jq.nix
    ./keybase.nix
    ./lazygit.nix
    ./lcov.nix
    ./less.nix
    ./luajit.nix
    ./luarocks.nix
    ./nil.nix
    ./nix-index.nix
    ./nix.nix
    ./nixd.nix
    ./nodejs_20.nix
    ./nvim
    ./oh-my-posh.nix
    ./rclone.nix
    ./ripgrep.nix
    ./rust.nix
    ./shellcheck.nix
    ./sops.nix
    ./sqlite.nix
    ./ssh.nix
    ./ssh-to-age.nix
    ./starship.nix
    ./statix.nix
    ./tmux.nix
    ./unzip.nix
    ./wget.nix
    ./xclip.nix
    ./zsh-fast-syntax-highlighting.nix
    ./zsh.nix
  ];
}
