{
  imports = [
    # FIXME: nix-tree
    ./code
    ./alejandra.nix
    ./aspell.nix
    ./bash-language-server.nix
    ./bash.nix
    ./bc.nix
    ./beautysh.nix
    ./bitwarden.nix
    ./btop.nix
    ./bun.nix
    ./cmake.nix
    ./curl.nix
    ./deadnix.nix
    ./dircolors.nix
    ./dnsutils.nix
    ./dotenv-linter.nix
    ./fblog.nix
    ./fd.nix
    ./fzf.nix
    ./gawk.nix
    ./gcc.nix
    ./git.nix
    ./gjs.nix
    ./gnumake.nix
    ./inotify-info.nix
    ./jq.nix
    ./json-lsp.nix
    ./keybase.nix
    ./lazygit.nix
    ./lcov.nix
    ./less.nix
    ./lua-language-server.nix
    ./luacheck.nix
    ./luajit.nix
    ./luarocks.nix
    ./markdownlint.nix
    ./marksman.nix
    ./nil.nix
    ./nix-index.nix
    ./nix-tree.nix
    ./nixd.nix
    ./nodejs_20.nix
    ./nvfetcher.nix
    ./nvim
    ./oh-my-posh.nix
    ./onlykey.nix
    ./poetry.nix
    ./prettierd.nix
    ./python_311.nix
    ./rclone
    ./ripgrep.nix
    ./rust.nix
    ./selene.nix
    ./shellcheck.nix
    ./shellharden.nix
    ./shfmt.nix
    ./sops.nix
    ./sqlite.nix
    ./ssh-to-age.nix
    ./ssh.nix
    ./starship.nix
    ./statix.nix
    ./stylua.nix
    ./tmux
    ./vim.nix
    ./wget.nix
    ./xclip.nix
    ./zip.nix
    ./zsh-fast-syntax-highlighting.nix
    ./zsh.nix
  ];
}
